### ISSUE TITLE
Edit on GitHub-link gets an 404

### ISSUE THREAD

**Issue by florianb** [apache/couchdb-documentation#512] opened 2020-03-30 16:06 UTC
Clicking on "Edit on GitHub" f.e. at this page: https://docs.couchdb.org/en/stable/index.html
returns an 404-error.

## Expected Behavior
I hoped i'd be redirected to the according GitHub-page.

## Current Behavior
404

## Possible Solution
I guess there's just a linkpath or something like that broken - give me a hint and i'll try to provide a PR.

## Steps to Reproduce (for bugs)
1. go to https://docs.couchdb.org/en/stable/index.html
2. click "Edit on GitHub" in the upper right corner.

## Context
Tried to fix the documentation.

## Your Environment
FF 75.0b9 (64-bit) on Ubuntu 19

**Comment by wohali** [comment] 2020-03-30 16:46
Hey @florianb ,

This is a readthedocs.org bug. The problem seems to be the commit they've chosen for the `stable` version. All the other versions bring up the correct "Edit on GitHub" link.

I'll take ths one.

**Comment by florianb** [comment] 2020-03-30 16:47
Thank you very much @wohali - give me a hint if i can help out!

**Comment by wohali** [comment] 2020-03-30 17:11
Looks like https://github.com/readthedocs/readthedocs.org/issues/1820 is the core issue here.

It should have been fixed per that issue report, but we're still seeing the bad behaviour: `stable` is a tag that points to this commit: f009601a which GH refuses to display (because that's the tag hash, not the commit hash.)

We had to move to `stable` being a tag for our release process. We can't go back to letting RTD determine what the latest semver tag is because we tag the documentation before we release now, meaning RTD "stable" may point to an unreleased version of documentation that can confuse users. (This happened for a few weeks during the 3.0.0 release cycle.)

If you're able to sleuth this further, let me know.

**Comment by florianb** [comment] 2020-03-31 08:29
Thanks a lot @wohali - it might be possible to manually set the target version of stable using [Automation Rules/Actions](https://docs.readthedocs.io/en/stable/automation-rules.html#actions).

It would be possible to map `stable` to f.e. `latest` or the given version number. To be able to do that i'd say that must be tightly integrated into the build process (using f.e. `envsubst`) to avoid future bugs.

If you'd like to see something like that, give me a hint - i'd probably give it a try.

**Comment by wohali** [comment] 2020-03-31 14:33
Hi @florianb ,

Sadly, that won't work, for two reasons.

The first is `stable` is already pointing at the same checkout as `3.0.0`. In fact this is how I did it manually:

```
git checkout 3.0.0
git tag <options> stable
git push origin --tags
```

The problem is that reference RTD is picking up is the tag hash, not the referred to git hash.

The second problem with your approach - which wouldn't change anything anyway - is because Apache explicitly disallows any automated action that changes the code repository. This is due to legal reasons necessary to protect the Foundation. I can dig up the LEGAL ticket on this if you need more clarification.

What's necessary here is to figure out why the fix in readthedocs/readthedocs.org#1820 isn't working for us.

**Comment by manjufy** [comment] 2020-04-26 08:40
The following link is broken too 
https://github.com/apache/couchdb-documentation/blob/f009601a29cef48114e238f70219d7413a5d759f/src/replication/index.rst

I was lead to the above page from https://docs.couchdb.org/en/stable/replication/index.html (Edit on the Github)

**Comment by wohali** [comment] 2020-04-27 20:42
Because this is hard to work out, I'm going to disable the per-page "Edit on Github" links for now. There will still be a nav to the GH repo available from the pop-up menu on the bottom left.

**Comment by wohali** [comment] 2020-04-27 20:52
Well, shoot. That didn't work.

**Comment by francwalter** [comment] 2020-05-03 09:19
> 
> 
> Because this is hard to work out, I'm going to disable the per-page "Edit on Github" links for now. There will still be a nav to the GH repo available from the pop-up menu on the bottom left.

[Edit on Github Link](https://github.com/apache/couchdb-documentation/blob/f009601a29cef48114e238f70219d7413a5d759f/src/index.rst) is still active and not working on [Apache CouchDB® 3.0.0 Documentation](https://docs.couchdb.org/en/stable/)

Thanks, frank

**Comment by wohali** [comment] 2020-05-03 19:03
Yup, that's why the issue was reopened.

**Comment by wohali** [comment] 2020-05-05 10:33
Fixed with a forced move of the `stable` tag.

**Closed by wohali** 2020-05-05 10:33 UTC
